///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TaskTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("774fa48e-569d-4151-a9c5-b94b55b2d771", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TaskTestRepository repository.
        /// </summary>
        public static TaskTestRepository repo = TaskTestRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SomeSvgTag' at 22;11.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SomeSvgTagInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SomeSvgTag.Click("22;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TuerkiyeninEnBueyuekOnlineAlışveriş1.Separator' at 48;19.", repo.TuerkiyeninEnBueyuekOnlineAlışveriş1.SeparatorInfo, new RecordItemIndex(1));
            repo.TuerkiyeninEnBueyuekOnlineAlışveriş1.Separator.Click("48;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TuerkiyeninEnBueyuekOnlineAlışveriş1.Geri' at 17;18.", repo.TuerkiyeninEnBueyuekOnlineAlışveriş1.GeriInfo, new RecordItemIndex(2));
            repo.TuerkiyeninEnBueyuekOnlineAlışveriş1.Geri.Click("17;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.GirişYap' at 44;10.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.GirişYapInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.GirişYap.Click("44;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.UEyeOl' at 36;17.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.UEyeOlInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.UEyeOl.Click("36;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.DivTagEPostaAdresiIleUeyeOl' at 96;19.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.DivTagEPostaAdresiIleUeyeOlInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.DivTagEPostaAdresiIleUeyeOl.Click("96;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TxtEmail' at 91;24.", repo.ApplicationUnderTest.TxtEmailInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.TxtEmail.Click("91;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.BtnSignUpSubmit' at 147;33.", repo.ApplicationUnderTest.BtnSignUpSubmitInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.BtnSignUpSubmit.Click("147;33");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.KişiselVerilerinizKapsamındaIşlenmekt' at 55;7.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.KişiselVerilerinizKapsamındaIşlenmektInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.KişiselVerilerinizKapsamındaIşlenmekt.Click("55;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.StrongTagAydınlatmaMetni' at 56;10.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.StrongTagAydınlatmaMetniInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.StrongTagAydınlatmaMetni.Click("56;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SomePathTag' at 3;5.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SomePathTagInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SomePathTag.Click("3;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.StrongTagUEyelikSoezleşmesi' at 313;5.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.StrongTagUEyelikSoezleşmesiInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.StrongTagUEyelikSoezleşmesi.Click("313;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.UEyelikSoezleşmesi' at 121;25.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.UEyelikSoezleşmesiInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.UEyelikSoezleşmesi.Click("121;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SomeSvgTag1' at 4;6.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SomeSvgTag1Info, new RecordItemIndex(13));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SomeSvgTag1.Click("4;6");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.StrongTagRızaMetni' at 34;7.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.StrongTagRızaMetniInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.StrongTagRızaMetni.Click("34;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.KişiselVerilerinIşlenmesineIlişkinRı' at 164;14.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.KişiselVerilerinIşlenmesineIlişkinRıInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.KişiselVerilerinIşlenmesineIlişkinRı.Click("164;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SomePathTag1' at 7;8.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SomePathTag1Info, new RecordItemIndex(16));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SomePathTag1.Click("7;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.StrongTagCerezPolitikası' at 45;8.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.StrongTagCerezPolitikasıInfo, new RecordItemIndex(17));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.StrongTagCerezPolitikası.Click("45;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.CerezPolitikası' at 125;22.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.CerezPolitikasıInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.CerezPolitikası.Click("125;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SomePathTag2' at 3;5.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SomePathTag2Info, new RecordItemIndex(19));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SomePathTag2.Click("3;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.DivTag1qzyrDtuo5Y1fZvzzhrn3' at 1042;380.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.DivTag1qzyrDtuo5Y1fZvzzhrn3Info, new RecordItemIndex(20));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.DivTag1qzyrDtuo5Y1fZvzzhrn3.Click("1042;380");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ApplicationUnderTest' at 1362;111.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(21));
            repo.ApplicationUnderTest.Self.MoveTo("1362;111");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1360;628.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.Self.Click("1360;628");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1360;628.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(23));
            repo.ApplicationUnderTest.Self.Click("1360;628");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1360;628.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(24));
            repo.ApplicationUnderTest.Self.Click("1360;628");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1360;628.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(25));
            repo.ApplicationUnderTest.Self.Click("1360;628");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1360;628.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.Self.Click("1360;628");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1360;628.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(27));
            repo.ApplicationUnderTest.Self.Click("1360;628");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1360;628.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(28));
            repo.ApplicationUnderTest.Self.Click("1360;628");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1360;628.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(29));
            repo.ApplicationUnderTest.Self.Click("1360;628");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1360;628.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(30));
            repo.ApplicationUnderTest.Self.Click("1360;628");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SosyalHesapIleGirişYap' at 163;15.", repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SosyalHesapIleGirişYapInfo, new RecordItemIndex(31));
            repo.ApplicationUnderTest.DivTag3GsvdTmLmWtmWX3ZOLPHU6FalseFals1.SosyalHesapIleGirişYap.Click("163;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTagGoogleIleGirişYap' at 54;3.", repo.ApplicationUnderTest.DivTagGoogleIleGirişYapInfo, new RecordItemIndex(32));
            repo.ApplicationUnderTest.DivTagGoogleIleGirişYap.Click("54;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OturumAcınGoogleHesapları.OturumAc' at 65;12.", repo.OturumAcınGoogleHesapları.OturumAcInfo, new RecordItemIndex(33));
            repo.OturumAcınGoogleHesapları.OturumAc.Click("65;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TuerkiyeninEnBueyuekOnlineAlışveriş1.Geri' at 23;21.", repo.TuerkiyeninEnBueyuekOnlineAlışveriş1.GeriInfo, new RecordItemIndex(34));
            repo.TuerkiyeninEnBueyuekOnlineAlışveriş1.Geri.Click("23;21");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1361;627.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(35));
            repo.ApplicationUnderTest.Self.Click("1361;627");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1361;627.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(36));
            repo.ApplicationUnderTest.Self.Click("1361;627");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1361;627.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(37));
            repo.ApplicationUnderTest.Self.Click("1361;627");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest' at 1361;627.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(38));
            repo.ApplicationUnderTest.Self.DoubleClick("1361;627");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1361;627.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(39));
            repo.ApplicationUnderTest.Self.Click("1361;627");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 1361;627.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(40));
            repo.ApplicationUnderTest.Self.Click("1361;627");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTagAppleIleGirişYap' at 42;12.", repo.ApplicationUnderTest.DivTagAppleIleGirişYapInfo, new RecordItemIndex(41));
            repo.ApplicationUnderTest.DivTagAppleIleGirişYap.Click("42;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TuerkiyeninEnBueyuekOnlineAlışveriş1.Geri' at 25;26.", repo.TuerkiyeninEnBueyuekOnlineAlışveriş1.GeriInfo, new RecordItemIndex(42));
            repo.TuerkiyeninEnBueyuekOnlineAlışveriş1.Geri.Click("25;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest' at 1362;629.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(43));
            repo.ApplicationUnderTest.Self.DoubleClick("1362;629");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ApplicationUnderTest' at 1362;629.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(44));
            repo.ApplicationUnderTest.Self.DoubleClick("1362;629");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DivTagFacebookIleGirişYap' at 31;11.", repo.ApplicationUnderTest.DivTagFacebookIleGirişYapInfo, new RecordItemIndex(45));
            repo.ApplicationUnderTest.DivTagFacebookIleGirişYap.Click("31;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TuerkiyeninEnBueyuekOnlineAlışveriş1.Geri' at 9;23.", repo.TuerkiyeninEnBueyuekOnlineAlışveriş1.GeriInfo, new RecordItemIndex(46));
            repo.TuerkiyeninEnBueyuekOnlineAlışveriş1.Geri.Click("9;23");
            Delay.Milliseconds(2760);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
